/* {ACTION_PREFIX}{ACTION_NAME} - ACTIONS GENERATED BY NGRX-HELPER */
export const {ACTION_PREFIX}{ACTION_NAME}Trigger = createAction('[{STORE_NAME}] {ACTION_PREFIX}{ACTION_NAME}Trigger',
    props<{ input: any }>()
)
export const {ACTION_PREFIX}{ACTION_NAME}Response = createAction('[{STORE_NAME}] {ACTION_PREFIX}{ACTION_NAME}Response',
    props<{ output: any }>()
)