
/* {EFFECT_PREFIX}{ACTION_NAME} - EFFECT GENERATED BY NGRX-HELPER */
{EFFECT_PREFIX}{ACTION_NAME}$ = createEffect(() =>
        this.actions$.pipe(
            ofType({ACTION_PREFIX}{ACTION_NAME}Trigger),
            switchMap(action => {
                const req$ = this.{storeName}Service.{actionName}$(action.input);
                return zip(of(action), req$)
            }),
            switchMap(([action, rsp]) => [
                {ACTION_PREFIX}{ACTION_NAME}Response({ output: rsp })
            ]),
            catchError((err, cought) => {
                console.error(err);
                return cought;
            })
        )
    )