/* {actionName} - SERVICE FUNCTION GENERATED BY NGRX-HELPER */
{actionName}$(val: string):Observable<any>{
    return of(`HELLO WORLD: [${val}], FROM YOUR {STORE_NAME}Service, the {actionName} function`);
}
